:config:
  :method: "WebivaNetHTTP"

:providers:
  :vimeo: "http://www.vimeo.com/api/oembed.{format}"
  :hulu: "http://www.hulu.com/api/oembed.{format}"
  :flickr: "http://www.flickr.com/services/oembed"
  :viddler: "http://lab.viddler.com/services/oembed/"
  :embedly: "http://api.embed.ly/v1/api/oembed"
  :youtube: "http://www.youtube.com/oembed"

:youtube:
  :format: "json"
  :schemes:
    - "http://*youtube.com/watch*"

:oohembed:
  :format: "json"
  :schemes:
    - "http://*.amazon.(com|co.uk|de|ca|jp)/*/(gp/product|o/ASIN|obidos/ASIN|dp)/*"
    - "http://*.amazon.(com|co.uk|de|ca|jp)/(gp/product|o/ASIN|obidos/ASIN|dp)/*"        
    - "http://*.collegehumor.com/video:*"
    - "http://*.funnyordie.com/videos/*"
    - "http://video.google.com/videoplay?*"
    - "http://*.imdb.com/title/tt*/"
    - "http://*.metacafe.com/watch/*"
    - "http://*.slideshare.net/*"
    - "http://twitter.com/*/statuses/*"
    - "http://*.wikipedia.org/wiki/*"
    - "http://*.wordpress.com/[0-9]{4}/[0-9]{2}/[0-9]{2}/*"

:vimeo:
  :format: "json"
  :schemes:
    - "http://www.vimeo.com/groups/*/*"
    - "http://www.vimeo.com/*"
    - "http://vimeo.com/groups/*/*"
    - "http://vimeo.com/*"

:hulu:
  :format: "xml"
  :schemes:
    - "http://www.hulu.com/watch/*"

:flickr:
  :format: "xml"
  :schemes:
    - "http://*.flickr.com/*"
    
:viddler:
  :format: "xml"
  :schemes:
    - "http://*.viddler.com/*"

:embedly:
  :format: "json"
  :schemes:
    - "http://youtu.be/*"
    - "http://www.veoh.com/*/watch/*"
    - "http://www.justin.tv/*"
    - "http://justin.tv/*"
    - "http://www.ustream.tv/recorded/*"
    - "http://www.ustream.tv/channel/*"
    - "http://qik.com/video/*"
    - "http://qik.com/*"
    - "http://*revision3.com/*"
    - "http://*.dailymotion.com/video/*"
    - "http://*.dailymotion.com/*/video/*"
    - "http://www.collegehumor.com/video:*"
    - "http://www.twitvid.com/*"
    - "http://www.break.com/*/*"
    - "http://vids.myspace.com/index.cfm?fuseaction=vids.individual&videoid*"
    - "http://www.myspace.com/index.cfm?fuseaction=*&videoid*"
    - "http://www.metacafe.com/watch/*"
    - "http://blip.tv/file/*"
    - "http://*.blip.tv/file/*"
    - "http://video.google.com/videoplay?*"
    - "http://revver.com/video/*"
    - "http://video.yahoo.com/watch/*/*"
    - "http://video.yahoo.com/network/*"
    - "http://liveleak.com/view?*"
    - "http://www.liveleak.com/view?*"
    - "http://animoto.com/play/*"
    - "http://dotsub.com/view/*"
    - "http://yfrog.*/*"
    - "http://tweetphoto.com/*"
    - "http://twitpic.com/*"
    - "http://*imgur.com/*"
    - "http://*.posterous.com/*"
    - "http://post.ly/*"
    - "http://twitgoo.com/*"
    - "http://i*.photobucket.com/albums/*"
    - "http://gi*.photobucket.com/groups/*"
    - "http://phodroid.com/*/*/*"
    - "http://xkcd.com/*"
    - "http://www.asofterworld.com/index.php?id=*"
    - "http://www.qwantz.com/index.php?comic=*"
    - "http://23hq.com/*/photo/*"
    - "http://www.23hq.com/*/photo/*"
    - "http://www.whitehouse.gov/photos-and-video/video/*"
    - "http://www.whitehouse.gov/video/*"
    - "http://wh.gov/photos-and-video/video/*"
    - "http://wh.gov/video/*"
    - "http://movieclips.com/watch/*/*/"
    - "http://movieclips.com/watch/*/*/*/*"
    - "http://*crackle.com/c/*"
    - "http://www.fancast.com/*/videos"
    - "http://www.funnyordie.com/videos/*"
    - "http://www.ted.com/talks/*.html*"
    - "http://www.ted.com/talks/lang/*/*.html*"
    - "http://www.ted.com/index.php/talks/*.html*"
    - "http://www.ted.com/index.php/talks/lang/*/*.html*"
    - "http://www.omnisio.com/*"
    - "http://*nfb.ca/film/*"
    - "http://www.thedailyshow.com/watch/*"
    - "http://www.thedailyshow.com/full-episodes/*"
    - "http://www.thedailyshow.com/collection/*/*/*"
    - "http://movies.yahoo.com/movie/*/video/*"
    - "http://movies.yahoo.com/movie/*/info"
    - "http://movies.yahoo.com/movie/*/trailer"
    - "http://www.colbertnation.com/the-colbert-report-collections/*"
    - "http://www.colbertnation.com/full-episodes/*"
    - "http://www.colbertnation.com/the-colbert-report-videos/*"
    - "http://www.comedycentral.com/videos/index.jhtml?*"
    - "http://www.theonion.com/video/*"
    - "http://theonion.com/video/*"
    - "http://wordpress.tv/*/*/*/*/"
    - "http://www.traileraddict.com/trailer/*"
    - "http://www.traileraddict.com/clip/*"
    - "http://www.traileraddict.com/poster/*"
    - "http://www.escapistmagazine.com/videos/*"
    - "http://soundcloud.com/*"
    - "http://soundcloud.com/*/*"
    - "http://soundcloud.com/*/sets/*"
    - "http://soundcloud.com/groups/*"
    - "http://www.lala.com/#album/*"
    - "http://www.lala.com/album/*"
    - "http://*amazon.*/gp/product/*"
    - "http://*amazon.*/*/dp/*"
    - "http://*amazon.*/dp/*"
    - "http://*amazon.*/o/ASIN/*"
    - "http://*amazon.*/gp/offer-listing/*"
    - "http://*amazon.*/*/ASIN/*"
    - "http://www.slideshare.net/*/*"
    - "http://*.scribd.com/doc/*"
    - "http://screenr.com/*"
    - "http://www.5min.com/Video/*"
    - "http://www.howcast.com/videos/*"
    - "http://www.screencast.com/*/media/*"
    - "http://screencast.com/*/media/*"
    - "http://www.screencast.com/t/*"
    - "http://screencast.com/t/*"
    - "http://www.clearspring.com/widgets/*"
    - "http://my.opera.com/*/albums/show.dml?id=*"
    - "http://my.opera.com/*/albums/showpic.dml?album=*&picture=*"
